# Generated by Django 5.2.2 on 2025-07-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subjectname',
        ),
    ]
